storage_credential_name = "unity-catalog-access-connector"
adb_container_name      = "data"
landing_container_name  = "landing"
account_name            = ""
config_catalog_name     = "config"
bronze_catalog_name     = "bronze"
config_schema           = "config"